name: trigger-by-tag-name
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Get the tag name
        run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}